name: Notify Discord on PR creation

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"📣 New Pull Request created by ${{ github.actor }} in *${{ github.repository }}*: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
